platform :ios, '9.0'

inhibit_all_warnings!

pod 'Parse', '~> 1.12'

pod 'SDWebImage', '~>3.7'
pod 'SVPullToRefresh'
pod 'Toast', '~> 3.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'ParseFacebookUtilsV4', '~> 1.11'
pod 'FBSDKCoreKit', '~> 4.9'
pod 'FBSDKLoginKit', '~> 4.9'
pod 'FBSDKShareKit', '~> 4.9'

pod 'MHPrettyDate', '~> 1.1'
pod 'DZNEmptyDataSet', '~> 1.7'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFDropdownNotification', '~> 1.0'

use_frameworks!